version: "3.8"
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"  
    networks:
      - app-network
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - expense-tracker1
      - expense-tracker2
  
  expense-tracker1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker1
    ports:
      - "8081:8080"
    environment:
      - APP_ENV=production

  expense-tracker2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker2
    ports:
      - "8082:8080"
    environment:
      - APP_ENV=production

volumes:
  redis-data:

networks:
  app-network:
